name: Publish to JSR

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4

            - uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Publish to JSR
              run: deno publish
